# Generated by Django 5.0.1 on 2024-01-28 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_contact_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
    ]
