# Generated by Django 5.0.1 on 2024-01-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
