# Generated by Django 5.0.1 on 2024-01-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_profile_address_profile_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
