# Generated by Django 5.0.1 on 2024-01-29 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
