# Generated by Django 5.0.1 on 2024-02-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_category_product_seller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
