# Generated by Django 5.0.1 on 2024-02-05 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_product_highest_bid_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='highest_bid',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
