# Generated by Django 5.0.1 on 2024-02-08 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_product_total_bids_bid_bidhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidhistory',
            old_name='bid_amount',
            new_name='amount',
        ),
    ]
