# Generated by Django 5.0.1 on 2024-02-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_rename_bid_amount_bidhistory_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='highest_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
