# Generated by Django 5.0.1 on 2024-02-08 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_product_highest_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='highest_bid',
        ),
    ]
