# Generated by Django 5.0.1 on 2024-02-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_alter_product_min_price_alter_product_price_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='highest_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
