# Generated by Django 5.0.1 on 2024-02-12 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_shippingdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdetails',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_details', to='crm.product'),
        ),
    ]
