# Generated by Django 5.0.1 on 2024-02-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_alter_shippingdetails_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdetails',
            name='shipping_details_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
