# Generated by Django 5.0.1 on 2024-02-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_shippingdetails_shipping_details_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingdetails',
            name='shipping_details_submitted',
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_details_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
