# Generated by Django 5.0.1 on 2024-02-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_shippingdetails_razor_pay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdetails',
            name='highest_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
