# Generated by Django 5.0.1 on 2024-02-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_shippingdetails_highest_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingdetails',
            name='highest_bid',
        ),
        migrations.AlterField(
            model_name='product',
            name='highest_bid',
            field=models.IntegerField(default=0),
        ),
    ]
