# Generated by Django 5.0.1 on 2024-02-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0036_remove_shippingdetails_highest_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='highest_bid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
