# Generated by Django 5.0.1 on 2024-02-14 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_shippingdetails_is_paid_alter_product_highest_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingdetails',
            name='is_paid',
        ),
    ]
