# Generated by Django 5.0.1 on 2024-02-15 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0042_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
    ]
